
-- A todo is a title, a completed status, and a description
-- It has a primary key as well as an optional remote key (generated by the Todoist API)

create table todos (
  id serial primary key,
  title varchar(255) not null,
  url varchar(255) not null,
  completed_on timestamp,
  remote_id bigint
);

