
-- A todo is a title, a completed status, and a description
-- It has a primary key as well as an optional remote key (generated by the Todoist API)

create table todos (
  id serial primary key,
  title text not null,
  url text ,
  completed_on timestamp,
  remote_id bigint
);

